# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_item',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
