# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_purchase_order_item_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_item',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
