# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_auto_20171110_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order_item',
            old_name='cost',
            new_name='buying_cost',
        ),
        migrations.AddField(
            model_name='purchase_order_item',
            name='selling_cost',
            field=models.FloatField(null=True),
        ),
    ]
