# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_auto_20171113_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_item',
            name='buying_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase_order_item',
            name='selling_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase_order_item',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
