# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
