# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_fish_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='sequence',
            field=models.IntegerField(unique=True),
        ),
    ]
