# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sales',
            field=models.FloatField(null=True),
        ),
    ]
