# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20171110_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice_item',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
