# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish', '0001_initial'),
        ('stall', '0001_initial'),
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(default='', max_length=50)),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_order.Purchase_Order')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stall.Stall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField()),
                ('weight', models.FloatField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.Fish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
